# Generated by Django 6.0.4 on 2026-05-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nm_cidade', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Eletroposto',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nm_eletroposto', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dados_api_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nm_estado', models.CharField(max_length=45)),
                ('cd_uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nm_bairro', models.CharField(max_length=45)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletropostos.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Conector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_tipo', models.CharField(max_length=45)),
                ('vl_potencia', models.IntegerField()),
                ('eletroposto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conectores', to='eletropostos.eletroposto')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletropostos.estado'),
        ),
        migrations.CreateModel(
            name='Lougradouro',
            fields=[
                ('id_lougradouro', models.AutoField(primary_key=True, serialize=False)),
                ('nm_lougradouro', models.CharField(max_length=100)),
                ('cd_cep', models.CharField(max_length=10)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletropostos.bairro')),
            ],
        ),
        migrations.AddField(
            model_name='eletroposto',
            name='lougradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletropostos.lougradouro'),
        ),
    ]
