# Generated by Django 6.0.4 on 2026-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletropostos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eletroposto',
            old_name='dados_api_json',
            new_name='dados_completos_json',
        ),
        migrations.RenameField(
            model_name='eletroposto',
            old_name='latitude',
            new_name='nm_latitude',
        ),
        migrations.RenameField(
            model_name='eletroposto',
            old_name='longitude',
            new_name='nm_longitude',
        ),
        migrations.AddField(
            model_name='eletroposto',
            name='cd_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
