# Generated by Django 6.0.4 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletropostos', '0002_rename_dados_api_json_eletroposto_dados_completos_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conector',
            name='nm_conector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
