# Generated by Django 6.0.4 on 2026-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletropostos', '0003_conector_nm_conector'),
    ]

    operations = [
        migrations.AddField(
            model_name='conector',
            name='vl_quantidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conector',
            name='vl_potencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
